---
name: Lucas
surname: van der Meer
position: "Doctoral Researcher in Geoinformatics"
address: "Salzburg, Austria"
profilepic: "./img/me.jpg"
email: "luukvandermeer@live.nl"
github: luukvdmeer
linkedin: luuk-van-der-meer
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 59C6B0
aboutme: "I am a doctoral researcher in geoinformatics at the University of Salzburg. I obtained a bachelor degree in Environmental & Infrastructure Planning from the University of Groningen, and a combined master degree in Geospatial Technologies from the universities of Lisbon, Castellon, and Münster. I am particularly interested in the application of geospatial data science to address socio-technical challenges regarding sustainable mobility, transport accessibility and livable cities."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("R","data.R"))

```

```{r funcs}
knit_print.vitae_dict <- function(x, options) {
  x[is.na(x)] <- ""
  if (isTRUE(attr(x, "protect"))) {
    protect_tex_input <- vitae:::protect_tex_input
  } else {
    protect_tex_input <- identity
  }
  entry_format_func <- function(with, why){
    why <- lapply(why, function(x) {
      if(length(x) == 0) {
        "{}\\vspace{-4.0mm}"
      } else {
        paste(c("{\\begin{cvitems}", paste("\\item", x), "\\end{cvitems}}"),
              collapse = "\n")
      }
    })
    paste(c(
      "\\begin{cventries}",
      vitae:::glue_alt("\t\\cvdict{<<with>>}<<why>>"),
      "\\end{cventries}"
    ), collapse = "\n")
  }
  knitr::asis_output(
    entry_format_func(
      protect_tex_input(x$with),
      protect_tex_input(x$why)
    )
  )
}

dict_entries <- function(data, ...) {
  obj <- detailed_entries(data, ...)
  obj_class <- class(obj)
  obj_class[1] <- "vitae_dict"
  class(obj) <- obj_class
  obj
}

knit_print.vitae_list <- function(x, options) {
  x[is.na(x)] <- ""
  if (isTRUE(attr(x, "protect"))) {
    protect_tex_input <- vitae:::protect_tex_input
  } else {
    protect_tex_input <- identity
  }
  entry_format_func <- function(why){
    why <- lapply(why, function(x) {
      if(length(x) == 0) {
        "{}\\vspace{-4.0mm}"
      } else {
        paste(c("{\\begin{cvenums}", paste("\\item", x), "\\end{cvenums}}"),
              collapse = "\n")
      }
    })
    paste(c(
      "\\begin{cventries}",
      vitae:::glue_alt("\t\\cvlist<<why>>"),
      "\\end{cventries}"
    ), collapse = "\n")
  }
  knitr::asis_output(
    entry_format_func(
      protect_tex_input(x$why)
    )
  )
}

list_entries <- function(data, ...) {
  obj <- detailed_entries(data, ...)
  obj_class <- class(obj)
  obj_class[1] <- "vitae_list"
  class(obj) <- obj_class
  obj
}

```

# Employment

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = description,
    when = glue::glue("{startMonth} {startYear} \\textemdash {endMonth} {endYear}",.na = ""),
    where = location,
    .protect = FALSE
  )

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = institute,
    what = degree,
    why = description,
    when = glue::glue("{startYear} \\textemdash {endYear}", .na = ""),
    where = location,
    .protect = FALSE
)
```

# Skills

```{r SKILLS}

skills %>%
  dict_entries(
    with = category,
    why = description,
    .protect = FALSE
)
```

# Selected publications

```{r PUBLICATIONS}

pub %>%
  list_entries(
    why = reference,
    .protect = FALSE
)

```

# Selected software

```{r SOFTWARE}

dev %>%
  list_entries(
    why = reference,
    .protect = FALSE
)

```

# Selected awards

```{r AWARDS}

awards %>%
  list_entries(
    why = reference,
    .protect = FALSE
)

```